upgrade script
Overv/openstreetmap-tile-server pull request #236
Opened 2021-12-27 10:39 UTC by Smartappli

- upgrade script 
- planet import
- leaflet bump version
- posgresql bump version
- postgis bump version

2021-12-29 11:18 UTC, Overv commented on upgrade.sh
> +set -x
I'd add more error flags to prevent this script from deleting the dump when importing was not successful, e.g.

```bash
set -euo pipefail
```

2021-12-29 11:18 UTC, Overv commented on README.md
> +### Upgrade from a previous version
With these manual upgrade steps we should probably also advice users to *never* run the latest version and always pin a specific one, with upgrade information added to releases.

2022-01-03 10:11 UTC, Smartappli commented on upgrade.sh
> +set -x
adapted

2022-01-03 10:11 UTC, Smartappli commented on README.md
> +### Upgrade from a previous version
warning notice added

2022-02-14 16:41 UTC, galewis2 requested changes

2022-02-14 16:41 UTC, galewis2 commented on upgrade.sh
> +set -euo pipefail
Make this more flexible/documentation changes only as shouldn't add more legacy code versions given that this PR is to move away from 12 entirely to 13.

2022-02-17 19:05 UTC, galewis2 commented
Superceded by https://github.com/Overv/openstreetmap-tile-server/pull/248, though the README/planet work from this may be useful. I'm closing this for now, but please feel free to open when just the README changes and some of the other things are in here!

2022-02-17 19:05 UTC, closed without merging