replace sudo with su. get rid of pesky sudo warning message
Overv/openstreetmap-tile-server pull request #238
Opened 2022-01-01 12:41 UTC by leakim

replace sudo with su. get rid of pesky sudo warning message: "sudo: unable to send audit message: Operation not permitted"

tested 2022-01-01

2022-01-03 09:34 UTC, Smartappli approved these changes

2022-02-16 20:33 UTC, galewis2 requested changes
Where is this specifically a problem? I'm not seeing any issues in a regular build with a recent version of Docker

2022-02-16 20:33 UTC, galewis2 commented on run.sh
> +  su - postgres -c "echo autovacuum = $AUTOVACUUM" >> /etc/postgresql/12/main/conf.d/postgresql.custom.conf
Where is this specifically a problem? I'm not seeing any issues in a regular build with a recent version of Docker

2022-06-14 13:30 UTC, galewis2 commented
Closing for now, please re-open and update if this is still a problem and it will be looked at again

2022-06-14 13:30 UTC, closed without merging