Fix volume permissions when using podman
Overv/openstreetmap-tile-server pull request #239
Opened 2022-01-01 13:17 UTC by leakim

2022-01-03 09:31 UTC, Smartappli approved these changes

2022-01-03 10:07 UTC, Smartappli approved these changes

2022-02-16 17:57 UTC, galewis2 commented
Given I don't have Podman, what's the best way to reproduce and test this?

2022-03-15 13:03 UTC, galewis2 requested changes
Given I don't have Podman, what's the best way to reproduce and test this?

2022-06-14 13:30 UTC, closed without merging