Add notes about running without internet connection
Overv/openstreetmap-tile-server pull request #250
Opened 2022-03-06 03:10 UTC by BudDavis

2022-03-10 13:07 UTC, galewis2 requested changes

2022-03-10 17:28 UTC, Istador commented
I always wondered what the use case for hosting an OSM tile server without internet connection is.

Are you running it as a service in a private network for other users/services in that network, and your corporate network security rules forbid you to access the internet?

If you just want tiles on your laptop for traveling while being offline, I'd just use a software like [Marble](https://wiki.openstreetmap.org/wiki/KDE_Marble) and let it download the tiles for the regions I'm interested in beforehand. There are even ways to configure offline routing and search.

2022-03-11 14:06 UTC, BudDavis commented
I work on systems that are air gapped from the internet.  No direct connection at any time.  Makes for some challenging situations.

2022-03-24 12:35 UTC, galewis2 approved these changes

2022-03-24 12:36 UTC, merged